-- ============================================================
-- Retail Sales Analytics | Raw Layer and Internal Stage
-- ============================================================

USE DATABASE RETAIL_DB;
USE SCHEMA RAW;

CREATE OR REPLACE TABLE CUSTOMER_RAW (
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR,
    GENDER VARCHAR,
    AGE NUMBER,
    CITY VARCHAR,
    STATE VARCHAR,
    SIGNUP_DATE DATE,
    CUSTOMER_SEGMENT VARCHAR
);

CREATE OR REPLACE TABLE PRODUCT_RAW (
    PRODUCT_ID VARCHAR,
    PRODUCT_NAME VARCHAR,
    CATEGORY VARCHAR,
    LIST_PRICE NUMBER(12,2),
    UNIT_COST NUMBER(12,2)
);

CREATE OR REPLACE TABLE ORDER_RAW (
    ORDER_ID NUMBER,
    CUSTOMER_ID NUMBER,
    ORDER_DATE DATE,
    CHANNEL VARCHAR,
    PAYMENT_METHOD VARCHAR,
    ORDER_STATUS VARCHAR
);

CREATE OR REPLACE TABLE ORDER_ITEM_RAW (
    ORDER_ITEM_ID NUMBER,
    ORDER_ID NUMBER,
    PRODUCT_ID VARCHAR,
    QUANTITY NUMBER,
    UNIT_PRICE NUMBER(12,2),
    DISCOUNT_PCT NUMBER(5,2),
    MARKETING_SPEND NUMBER(12,2)
);

CREATE OR REPLACE TABLE RETURNS_RAW (
    RETURN_ID VARCHAR,
    ORDER_ID NUMBER,
    RETURN_DATE DATE,
    RETURN_REASON VARCHAR,
    REFUND_STATUS VARCHAR
);

CREATE OR REPLACE TABLE MARKETING_RAW (
    MONTH DATE,
    CAMPAIGN VARCHAR,
    CAMPAIGN_SPEND NUMBER(12,2),
    IMPRESSIONS NUMBER,
    CLICKS NUMBER,
    LEADS NUMBER
);

CREATE OR REPLACE FILE FORMAT RETAIL_DB.RAW.RETAIL_CSV_FORMAT
    TYPE = 'CSV'
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    NULL_IF = ('', 'NULL', 'NaN')
    EMPTY_FIELD_AS_NULL = TRUE;

CREATE OR REPLACE STAGE RETAIL_DB.RAW.RETAIL_STAGE
    FILE_FORMAT = RETAIL_DB.RAW.RETAIL_CSV_FORMAT;

-- Upload the six cleaned CSV files to @RETAIL_DB.RAW.RETAIL_STAGE
-- before running 03_raw_load.sql.
