-- ============================================================
-- Retail Sales Analytics | Load Six Cleaned CSV Files
-- ============================================================

USE DATABASE RETAIL_DB;
USE SCHEMA RAW;

COPY INTO CUSTOMER_RAW
FROM @RETAIL_STAGE/customer_clean.csv
FILE_FORMAT = (FORMAT_NAME = RETAIL_CSV_FORMAT)
ON_ERROR = 'ABORT_STATEMENT';

COPY INTO ORDER_RAW
FROM @RETAIL_STAGE/order_clean.csv
FILE_FORMAT = (FORMAT_NAME = RETAIL_CSV_FORMAT)
ON_ERROR = 'ABORT_STATEMENT';

COPY INTO ORDER_ITEM_RAW
FROM @RETAIL_STAGE/order_item_clean.csv
FILE_FORMAT = (FORMAT_NAME = RETAIL_CSV_FORMAT)
ON_ERROR = 'ABORT_STATEMENT';

COPY INTO PRODUCT_RAW
FROM @RETAIL_STAGE/product_clean.csv
FILE_FORMAT = (FORMAT_NAME = RETAIL_CSV_FORMAT)
ON_ERROR = 'ABORT_STATEMENT';

COPY INTO RETURNS_RAW
FROM @RETAIL_STAGE/returns_clean.csv
FILE_FORMAT = (FORMAT_NAME = RETAIL_CSV_FORMAT)
ON_ERROR = 'ABORT_STATEMENT';

COPY INTO MARKETING_RAW
FROM @RETAIL_STAGE/marketing_clean.csv
FILE_FORMAT = (FORMAT_NAME = RETAIL_CSV_FORMAT)
ON_ERROR = 'ABORT_STATEMENT';

-- Basic load verification
SELECT COUNT(*) AS CUSTOMER_ROWS FROM CUSTOMER_RAW;
SELECT COUNT(*) AS ORDER_ROWS FROM ORDER_RAW;
SELECT COUNT(*) AS ORDER_ITEM_ROWS FROM ORDER_ITEM_RAW;
SELECT COUNT(*) AS PRODUCT_ROWS FROM PRODUCT_RAW;
SELECT COUNT(*) AS RETURN_ROWS FROM RETURNS_RAW;
SELECT COUNT(*) AS MARKETING_ROWS FROM MARKETING_RAW;

-- Discount quality check
SELECT
    COUNT_IF(DISCOUNT_PCT = 0) AS ZERO_DISCOUNT,
    COUNT_IF(DISCOUNT_PCT IS NULL) AS MISSING_DISCOUNT
FROM ORDER_ITEM_RAW;
