-- ============================================================
-- Retail Sales Analytics | Staging and Business Calculations
-- ============================================================

USE DATABASE RETAIL_DB;
USE SCHEMA STAGING;

CREATE OR REPLACE TABLE CUSTOMER_STG AS
SELECT * FROM RETAIL_DB.RAW.CUSTOMER_RAW;

CREATE OR REPLACE TABLE ORDER_STG AS
SELECT * FROM RETAIL_DB.RAW.ORDER_RAW;

CREATE OR REPLACE TABLE ORDER_ITEM_STG AS
SELECT * FROM RETAIL_DB.RAW.ORDER_ITEM_RAW;

CREATE OR REPLACE TABLE PRODUCT_STG AS
SELECT * FROM RETAIL_DB.RAW.PRODUCT_RAW;

CREATE OR REPLACE TABLE RETURNS_STG AS
SELECT * FROM RETAIL_DB.RAW.RETURNS_RAW;

CREATE OR REPLACE TABLE MARKETING_STG AS
SELECT * FROM RETAIL_DB.RAW.MARKETING_RAW;

-- Staging row-count verification
SELECT COUNT(*) AS CUSTOMER_STG_ROWS FROM CUSTOMER_STG;
SELECT COUNT(*) AS ORDER_STG_ROWS FROM ORDER_STG;
SELECT COUNT(*) AS ORDER_ITEM_STG_ROWS FROM ORDER_ITEM_STG;
SELECT COUNT(*) AS PRODUCT_STG_ROWS FROM PRODUCT_STG;
SELECT COUNT(*) AS RETURNS_STG_ROWS FROM RETURNS_STG;
SELECT COUNT(*) AS MARKETING_STG_ROWS FROM MARKETING_STG;

-- Gross sales
SELECT
    ORDER_ITEM_ID,
    ORDER_ID,
    PRODUCT_ID,
    QUANTITY,
    UNIT_PRICE,
    QUANTITY * UNIT_PRICE AS GROSS_SALES,
    DISCOUNT_PCT,
    MARKETING_SPEND
FROM ORDER_ITEM_STG
LIMIT 10;

-- Discount amount and net sales
SELECT
    ORDER_ITEM_ID,
    ORDER_ID,
    PRODUCT_ID,
    QUANTITY,
    UNIT_PRICE,
    DISCOUNT_PCT,
    QUANTITY * UNIT_PRICE AS GROSS_SALES,
    CASE
        WHEN DISCOUNT_PCT IS NOT NULL
        THEN (QUANTITY * UNIT_PRICE) * (DISCOUNT_PCT / 100)
    END AS DISCOUNT_AMOUNT,
    CASE
        WHEN DISCOUNT_PCT IS NOT NULL
        THEN (QUANTITY * UNIT_PRICE)
             - ((QUANTITY * UNIT_PRICE) * (DISCOUNT_PCT / 100))
    END AS NET_SALES
FROM ORDER_ITEM_STG
LIMIT 20;

-- Review records with missing discount
SELECT
    ORDER_ITEM_ID,
    ORDER_ID,
    QUANTITY,
    UNIT_PRICE,
    DISCOUNT_PCT,
    QUANTITY * UNIT_PRICE AS GROSS_SALES,
    CASE
        WHEN DISCOUNT_PCT IS NOT NULL
        THEN (QUANTITY * UNIT_PRICE) * (DISCOUNT_PCT / 100)
    END AS DISCOUNT_AMOUNT,
    CASE
        WHEN DISCOUNT_PCT IS NOT NULL
        THEN (QUANTITY * UNIT_PRICE) * (1 - DISCOUNT_PCT / 100)
    END AS NET_SALES
FROM ORDER_ITEM_STG
WHERE DISCOUNT_PCT IS NULL;

-- Join order items to products
SELECT
    oi.ORDER_ITEM_ID,
    oi.ORDER_ID,
    oi.PRODUCT_ID,
    p.PRODUCT_NAME,
    p.CATEGORY,
    oi.QUANTITY,
    oi.UNIT_PRICE,
    p.UNIT_COST,
    oi.DISCOUNT_PCT,
    oi.QUANTITY * oi.UNIT_PRICE AS GROSS_SALES,
    CASE
        WHEN oi.DISCOUNT_PCT IS NOT NULL
        THEN (oi.QUANTITY * oi.UNIT_PRICE)
             * (oi.DISCOUNT_PCT / 100)
    END AS DISCOUNT_AMOUNT,
    CASE
        WHEN oi.DISCOUNT_PCT IS NOT NULL
        THEN (oi.QUANTITY * oi.UNIT_PRICE)
             * (1 - oi.DISCOUNT_PCT / 100)
    END AS NET_SALES,
    oi.QUANTITY * p.UNIT_COST AS TOTAL_COST
FROM ORDER_ITEM_STG AS oi
JOIN PRODUCT_STG AS p
    ON oi.PRODUCT_ID = p.PRODUCT_ID
LIMIT 20;

-- Add profit
SELECT
    oi.ORDER_ITEM_ID,
    oi.ORDER_ID,
    oi.PRODUCT_ID,
    p.PRODUCT_NAME,
    p.CATEGORY,
    oi.QUANTITY,
    oi.UNIT_PRICE,
    p.UNIT_COST,
    oi.DISCOUNT_PCT,
    oi.QUANTITY * oi.UNIT_PRICE AS GROSS_SALES,
    CASE
        WHEN oi.DISCOUNT_PCT IS NOT NULL
        THEN (oi.QUANTITY * oi.UNIT_PRICE)
             * (oi.DISCOUNT_PCT / 100)
    END AS DISCOUNT_AMOUNT,
    CASE
        WHEN oi.DISCOUNT_PCT IS NOT NULL
        THEN (oi.QUANTITY * oi.UNIT_PRICE)
             * (1 - oi.DISCOUNT_PCT / 100)
    END AS NET_SALES,
    oi.QUANTITY * p.UNIT_COST AS TOTAL_COST,
    CASE
        WHEN oi.DISCOUNT_PCT IS NOT NULL
        THEN (
            (oi.QUANTITY * oi.UNIT_PRICE)
            - ((oi.QUANTITY * oi.UNIT_PRICE)
               * (oi.DISCOUNT_PCT / 100))
        )
        - (oi.QUANTITY * p.UNIT_COST)
    END AS PROFIT
FROM ORDER_ITEM_STG AS oi
JOIN PRODUCT_STG AS p
    ON oi.PRODUCT_ID = p.PRODUCT_ID
LIMIT 20;
