-- ============================================================
-- Retail Sales Analytics | Incremental Customer Automation
-- Stream -> Task -> MERGE
-- ============================================================

USE DATABASE RETAIL_DB;

CREATE OR REPLACE STREAM RAW.CUSTOMER_STREAM
    ON TABLE RAW.CUSTOMER_RAW;

-- Optional one-time manual execution for testing.
MERGE INTO STAGING.CUSTOMER_STG AS TARGET
USING RAW.CUSTOMER_STREAM AS SOURCE
    ON TARGET.CUSTOMER_ID = SOURCE.CUSTOMER_ID

WHEN MATCHED THEN
    UPDATE SET
        CUSTOMER_NAME = SOURCE.CUSTOMER_NAME,
        GENDER = SOURCE.GENDER,
        AGE = SOURCE.AGE,
        CITY = SOURCE.CITY,
        STATE = SOURCE.STATE,
        SIGNUP_DATE = SOURCE.SIGNUP_DATE,
        CUSTOMER_SEGMENT = SOURCE.CUSTOMER_SEGMENT

WHEN NOT MATCHED THEN
    INSERT (
        CUSTOMER_ID,
        CUSTOMER_NAME,
        GENDER,
        AGE,
        CITY,
        STATE,
        SIGNUP_DATE,
        CUSTOMER_SEGMENT
    )
    VALUES (
        SOURCE.CUSTOMER_ID,
        SOURCE.CUSTOMER_NAME,
        SOURCE.GENDER,
        SOURCE.AGE,
        SOURCE.CITY,
        SOURCE.STATE,
        SOURCE.SIGNUP_DATE,
        SOURCE.CUSTOMER_SEGMENT
    );

CREATE OR REPLACE TASK RETAIL_DB.STAGING.CUSTOMER_LOAD_TASK
    WAREHOUSE = RETAIL_WH
    SCHEDULE = '1 MINUTE'
    WHEN SYSTEM$STREAM_HAS_DATA('RETAIL_DB.RAW.CUSTOMER_STREAM')
AS
    MERGE INTO RETAIL_DB.STAGING.CUSTOMER_STG AS TARGET
    USING RETAIL_DB.RAW.CUSTOMER_STREAM AS SOURCE
        ON TARGET.CUSTOMER_ID = SOURCE.CUSTOMER_ID

    WHEN MATCHED THEN
        UPDATE SET
            CUSTOMER_NAME = SOURCE.CUSTOMER_NAME,
            GENDER = SOURCE.GENDER,
            AGE = SOURCE.AGE,
            CITY = SOURCE.CITY,
            STATE = SOURCE.STATE,
            SIGNUP_DATE = SOURCE.SIGNUP_DATE,
            CUSTOMER_SEGMENT = SOURCE.CUSTOMER_SEGMENT

    WHEN NOT MATCHED THEN
        INSERT (
            CUSTOMER_ID,
            CUSTOMER_NAME,
            GENDER,
            AGE,
            CITY,
            STATE,
            SIGNUP_DATE,
            CUSTOMER_SEGMENT
        )
        VALUES (
            SOURCE.CUSTOMER_ID,
            SOURCE.CUSTOMER_NAME,
            SOURCE.GENDER,
            SOURCE.AGE,
            SOURCE.CITY,
            SOURCE.STATE,
            SOURCE.SIGNUP_DATE,
            SOURCE.CUSTOMER_SEGMENT
        );

ALTER TASK RETAIL_DB.STAGING.CUSTOMER_LOAD_TASK RESUME;

SHOW TASKS IN SCHEMA RETAIL_DB.STAGING;
