-- ============================================================
-- Retail Sales Analytics | Validation Queries
-- ============================================================

USE DATABASE RETAIL_DB;

SELECT 'CUSTOMER_RAW' AS TABLE_NAME, COUNT(*) AS ROW_COUNT
FROM RAW.CUSTOMER_RAW
UNION ALL
SELECT 'ORDER_RAW', COUNT(*) FROM RAW.ORDER_RAW
UNION ALL
SELECT 'ORDER_ITEM_RAW', COUNT(*) FROM RAW.ORDER_ITEM_RAW
UNION ALL
SELECT 'PRODUCT_RAW', COUNT(*) FROM RAW.PRODUCT_RAW
UNION ALL
SELECT 'RETURNS_RAW', COUNT(*) FROM RAW.RETURNS_RAW
UNION ALL
SELECT 'MARKETING_RAW', COUNT(*) FROM RAW.MARKETING_RAW;

SELECT
    'CUSTOMER_STG' AS TABLE_NAME,
    COUNT(*) AS ROW_COUNT
FROM STAGING.CUSTOMER_STG
UNION ALL
SELECT 'ORDER_STG', COUNT(*) FROM STAGING.ORDER_STG
UNION ALL
SELECT 'ORDER_ITEM_STG', COUNT(*) FROM STAGING.ORDER_ITEM_STG
UNION ALL
SELECT 'PRODUCT_STG', COUNT(*) FROM STAGING.PRODUCT_STG
UNION ALL
SELECT 'RETURNS_STG', COUNT(*) FROM STAGING.RETURNS_STG
UNION ALL
SELECT 'MARKETING_STG', COUNT(*) FROM STAGING.MARKETING_STG;

SELECT
    'DIM_CUSTOMER' AS TABLE_NAME,
    COUNT(*) AS ROW_COUNT
FROM ANALYTICS.DIM_CUSTOMER
UNION ALL
SELECT 'DIM_PRODUCT', COUNT(*) FROM ANALYTICS.DIM_PRODUCT
UNION ALL
SELECT 'DIM_DATE', COUNT(*) FROM ANALYTICS.DIM_DATE
UNION ALL
SELECT 'FACT_SALES', COUNT(*) FROM ANALYTICS.FACT_SALES;

SELECT
    COUNT(*) AS TOTAL_FACT_ROWS,
    COUNT_IF(GROSS_SALES IS NULL) AS NULL_GROSS_SALES,
    COUNT_IF(NET_SALES IS NULL) AS NULL_NET_SALES,
    COUNT_IF(PROFIT IS NULL) AS NULL_PROFIT
FROM ANALYTICS.FACT_SALES;

SELECT *
FROM STAGING.CUSTOMER_STG
WHERE CUSTOMER_ID = 1701;
