# -*- coding: utf-8 -*-
"""retail_project_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qJ-o1MloeDmrOBiecfms-9jGkdmXRzZc
"""

import pandas as pd

customer = pd.read_csv("customers_raw.csv")
marketing = pd.read_csv("marketing_raw.csv")
order_item = pd.read_csv("order_items_raw.csv")
order = pd.read_csv("orders_raw.csv")
product = pd.read_csv("products_raw.csv")
returns  = pd.read_csv("returns_raw.csv")

print("customers :",customer.shape)
print("marketing :",marketing.shape)
print("order_item :",order_item.shape)
print("order :",order.shape)
print("product :",product.shape)
print("returns :",returns.shape)

# Understand the columns
print(customer.columns)
print(marketing.columns)
print(order_item.columns)
print(order.columns)
print(product.columns)
print(returns.columns)

## Data Profiling
print(customer.info())
print(marketing.info())
print(order_item.info())
print(order.info())
print(product.info())
print(returns.info())

## Missing-value profiling
customer.isnull().sum()

marketing.isnull().sum()

order_item.isnull().sum()

order.isnull().sum()

product.isnull().sum()

returns.isnull().sum()

## Duplicate Analysis
print("customer :",customer.duplicated().sum())
print("marketing :",marketing.duplicated().sum())
print("order_item :",order_item.duplicated().sum())
print("order :",order.duplicated().sum())
print("product :",product.duplicated().sum())
print("returns :",returns.duplicated().sum())

print("customer_id :",customer['customer_id'].duplicated().sum())
print("product_id :",product["product_id"].duplicated().sum())
print("order_id :",order["order_id"].duplicated().sum())
print("order_items_id :",order_item["order_item_id"].duplicated().sum())
print("return_id :",returns["return_id"].duplicated().sum())

## Inspect the actual duplicates
customer[
    customer["customer_id"].duplicated(keep=False)
].sort_values("customer_id")

order[
    order["order_id"].duplicated(keep=False)
].sort_values("order_id")

order_item[
    order_item["order_item_id"].duplicated(keep=False)
].sort_values("order_item_id")

## Categorical Value Consistency
## for cusstomer
print(customer["gender"].value_counts(dropna=False))
print(customer["city"].value_counts(dropna=False))
print(customer["state"].value_counts(dropna=False))
print(customer["customer_segment"].value_counts(dropna=False))

##for orders
print(order["channel"].value_counts(dropna=False))
print(order["payment_method"].value_counts(dropna=False))
print(order["order_status"].value_counts(dropna=False))

#for product
print(product["category"].value_counts(dropna=False))

## for returns
print(returns["return_reason"].value_counts(dropna=False))
print(returns["refund_status"].value_counts(dropna=False))

## Numeric data quality
customer["age"].describe()

order_item[["quantity", "unit_price", "discount_pct", "marketing_spend"]].describe()

product[["list_price", "unit_cost"]].describe()

marketing[[
    "campaign_spend", "impressions", "clicks", "leads"
]].describe()

order_item[order_item["quantity"]==0]

order_item["quantity"].value_counts().sort_index()

## referencing integrity
order["customer_id"].isin(customer["customer_id"]).value_counts()

order_item["order_id"].isin(order["order_id"]).value_counts()

order_item["product_id"].isin(product["product_id"]).value_counts()

returns["order_id"].isin(order["order_id"]).value_counts()

## Preserve raw data
customer_clean = customer.copy()
order_clean = order.copy()
order_item_clean = order_item.copy()
product_clean = product.copy()
returns_clean = returns.copy()
marketing_clean = marketing.copy()

"""# Data Claening"""

## check the clean data counts
customer_before = len(customer_clean)
order_before = len(order_clean)
order_item_before = len(order_item_clean)

## remove exact duplicates
customer_clean = customer_clean.drop_duplicates()
order_clean = order_clean.drop_duplicates()
order_item_clean = order_item_clean.drop_duplicates()

## Standardize categorical values

## for customer city
customer_clean["city"] = customer_clean["city"].replace({"delhi":"Delhi"})

## for order channel
order_clean["channel"] = order_clean["channel"].replace({"online":"Online"})

## for product
product_clean["category"] = product_clean["category"].replace({"electronics":"Electronics"})

product_clean["category"].value_counts(dropna=False)

## remove unwanted spaces
## for customer

customer_clean["gender"] = customer_clean["gender"].str.strip()
customer_clean["city"] = customer_clean["city"].str.strip()
customer_clean["state"] = customer_clean["state"].str.strip()
customer_clean["customer_segment"] = customer_clean["customer_segment"].str.strip()

## for order
order_clean["channel"] = order_clean["channel"].str.strip()
order_clean["payment_method"] = order_clean["payment_method"].str.strip()
order_clean["order_status"] = order_clean["order_status"].str.strip()

## for product
product_clean["product_name"] = product_clean["product_name"].str.strip()
product_clean["category"] = product_clean["category"].str.strip()

## missing-value treatment.
## check whose are fit mean vs meadian

print(customer_clean["age"].describe())

## check distribution of age
customer_clean["age"].value_counts().sort_index()

## age convert into integer data type
customer_clean["age"] = customer_clean["age"].astype(int)

## fill age with median
customer_clean["age"] = customer_clean["age"].fillna(customer_clean["age"].median())

## check the missing values
customer_clean["age"].isnull().sum()

## check the customer segment

customer_clean["customer_segment"].value_counts(dropna=False)

## fill with the unknown values
customer_clean["customer_segment"] = customer_clean["customer_segment"].fillna("Unknown")

## verify the data
customer_clean["customer_segment"].value_counts(dropna=False)

customer_clean["customer_segment"].isnull().sum()

## for payment method fill with unknown data
order_clean["payment_method"] = order_clean["payment_method"].fillna("Unknown")

## verify
print(order_clean["payment_method"].value_counts(dropna=False))
print(order_clean["payment_method"].isnull().sum())

## check marketing spend
print(order_item_clean["marketing_spend"].describe())
print(order_item_clean["marketing_spend"].isnull().sum())

## for return reason fill with unknown values
returns_clean["return_reason"] = returns_clean["return_reason"].fillna("Unknown")

## verify the return reason
returns_clean["return_reason"].value_counts(dropna=False)

"""# Data Type Convert"""

## convert signup date columns into date type
customer_clean["signup_date"] = pd.to_datetime(customer_clean["signup_date"])

#verify
customer_clean["signup_date"].dtype

## convert order date into date type
order_clean["order_date"] = pd.to_datetime(order_clean["order_date"])

## verify
order_clean["order_date"].dtype

## convert return date into date type
returns_clean["return_date"] = pd.to_datetime(returns_clean["return_date"])

## verify
returns_clean["return_date"].dtype

## month date into date type
marketing_clean["month"] = pd.to_datetime(marketing_clean["month"])

## verify
marketing_clean["month"].dtype

## Check quantity
order_item_clean["quantity"].value_counts().sort_index()

order_item_clean["quantity"].describe()

order_item_clean[
    order_item_clean["quantity"]<=0
]

## remove invalid data from quantity
order_item_clean = order_item_clean[
    order_item_clean["quantity"]>0
].copy()

## Check unit_price
order_item_clean["unit_price"].describe()

order_item_clean[
    order_item_clean["unit_price"]<=0
]

## Check product prices and costs
product_clean[["list_price", "unit_cost"]].describe()

product_clean[
    (product_clean["list_price"]<=0)|
    (product_clean["unit_cost"]<=0)
]

product_clean[
    product_clean["unit_cost"]>=product_clean["list_price"]
]

## validate discounts
order_item_clean[
    (order_item_clean["discount_pct"]<0)|
    (order_item_clean["discount_pct"]>100)
]

## check marketing_spend:
order_item_clean[order_item_clean["marketing_spend"]<0]

"""# Check Final Data Validation"""

print("Customer:", customer_clean.shape)
print("Marketing:", marketing_clean.shape)
print("Order Item:", order_item_clean.shape)
print("Order:", order_clean.shape)
print("Product:", product_clean.shape)
print("Returns:", returns_clean.shape)

print(customer_clean.isnull().sum())
print(order_clean.isnull().sum())
print(order_item_clean.isnull().sum())
print(product_clean.isnull().sum())
print(returns_clean.isnull().sum())
print(marketing_clean.isnull().sum())

print("Customer duplicates:", customer_clean.duplicated().sum())
print("Order duplicates:", order_clean.duplicated().sum())
print("Order Item duplicates:", order_item_clean.duplicated().sum())
print("Product duplicates:", product_clean.duplicated().sum())
print("Returns duplicates:", returns_clean.duplicated().sum())
print("Marketing duplicates:", marketing_clean.duplicated().sum())

customer_clean.info()
order_clean.info()
order_item_clean.info()
product_clean.info()
returns_clean.info()
marketing_clean.info()

"""# Export Cleaned Datasets"""

customer_clean.to_csv("customer_clean.csv", index=False)
order_clean.to_csv("order_clean.csv", index=False)
order_item_clean.to_csv("order_item_clean.csv", index=False)
product_clean.to_csv("product_clean.csv", index=False)
marketing_clean.to_csv("marketing_clean.csv", index=False)
returns_clean.to_csv("returns_clean.csv", index=False)

## check the save files
!ls

## download all files in as zip
!zip clean_retail_data.zip customer_clean.csv marketing_clean.csv order_item_clean.csv order_clean.csv product_clean.csv returns_clean.csv

from google.colab import files
files.download("clean_retail_data.zip")